### PR TITLE
Web edits

### LINKED ISSUE #93: Change answer feedback methods
We don't really need to display sounds when the question is answered in a correct or wrong way,
Making an animation (like shaking the wrong answer tile) when the question is answered incorrectly or displaying some glitter when the question is answered correctly are very enough.

That'll spare us the need to serve large assets from the server

### PR DESCRIPTION
**Pull request by ahmedhammad97**
Fixed #93 #94

### CODE REVIEW

File: app/src/main/web/src/components/GameComponents/QuestionBody.vue [hunk 1]
```diff
@@ -23,4 +37,10 @@ h1{
   width: 70%;
   margin: auto;
 }
+.correct{
```
Comment (shakram02) [inline app/src/main/web/src/components/GameComponents/QuestionBody.vue:40]: can it be animated? just changing the color might go unnoticed, also note that the color must match the theme

File: app/src/main/web/src/components/GamePage.vue [hunk 2]
```diff
@@ -51,7 +51,7 @@ export default {
       questions : [],
       questionIndex: 0,
       failed: true,
-      testing: false,
+      testing: true,
```
Comment (shakram02) [inline app/src/main/web/src/components/GamePage.vue]: can we take this into a configuration file? because I also need to modify the IP to match the test server's IP

File: app/src/main/web/src/components/GamePage.vue [hunk 3]
```diff
@@ -62,7 +62,7 @@ export default {
     correctAnswer: function(){
       return this.questions[this.questionIndex].correct;
     },
-    possibleAnswers: function(){
+    PossibleAnswers: function(){
```
Comment (shakram02) [inline app/src/main/web/src/components/GamePage.vue:66]: can you please check the naming conventions here?

**Review by shakram02 — CHANGES_REQUESTED** [review]
please check the edits

File: app/src/main/web/src/components/GamePage.vue (hunk 3 above)
Comment (ahmedhammad97) [reply app/src/main/web/src/components/GamePage.vue:66]: Yes, I meant to change it as it was causing some confusion.
I made sure it's consistent else where.

File: app/src/main/web/src/components/GameComponents/QuestionBody.vue (hunk 1 above)
Comment (ahmedhammad97) [reply app/src/main/web/src/components/GameComponents/QuestionBody.vue:40]: Would a vertical vibration for the correct answer, and horizontal vibration for wrong answer do the job?

Comment (shakram02) [reply app/src/main/web/src/components/GameComponents/QuestionBody.vue:40]: yup

File: app/src/main/web/src/components/GamePage.vue (hunk 2 above)
Comment (ahmedhammad97) [reply app/src/main/web/src/components/GamePage.vue]: I think it is possible. I have some unknowns there though, I'll try figure it out.

Comment (ahmedhammad97) [reply app/src/main/web/src/components/GamePage.vue]: I think we are not allowed to embed our custom configs into `vue.config` file or other config files, so for now I added a `configs.js` file, which can contain our custom configs.
Let me know if this isn't what we're looking for.
